### ISSUE TITLE
US Population Rankings chart JPG not shown

### ISSUE THREAD

**Issue by E3V3A** [aaronpenne/Data_Visualization#1]
Hi! 
Thanks for sharing this great code and data. Very cool and very nicely done! 

![firefox_2018-09-02_21-47-51](https://user-images.githubusercontent.com/194392/44959624-18b21a00-aee1-11e8-8a8a-538639d14cef.png)

**Comment by aaronpenne** [comment]
Looks like I broke a link by making my github.io repo private. Thanks for the heads up @E3V3A
